import React from 'react'
import { Meta, Story } from '@storybook/react'
import Table from '../src'
import { TableProps } from '../src/types'

const meta: Meta = {
  title: 'Table',
  component: Table,
  argTypes: {
    title: {
      description: 'Title',
      control: {
        type: 'text',
      },
    },
    data: {
      description: 'Input data',
      control: {
        type: 'object',
      },
    },
    columns: {
      description: 'Column to data key mapping',
      control: {
        type: 'object',
      },
    },
    theme: {
      description: 'Theme',
      control: {
        type: 'object',
      },
    },
  },
  parameters: {
    controls: { expanded: true },
  },
}

export default meta

const Template: Story<TableProps> = args => <Table {...args} />

const data = [
  {
    operator: '*Celcom Axiata (LTE)',
    headset_display: 'CELCOM / My Celcom / 502 19',
    '3g_availability': true,
  },
  {
    operator: '*DiGi Telecom (LTE)',
    headset_display: 'DiGi 1800 / DiGi / MYMY18',
    '3g_availability': true,
  },
  {
    operator: '*Maxis (LTE)',
    headset_display: 'U Mobile / MYS 18 / MY18',
    '3g_availability': true,
  },
  {
    operator: 'U Mobile (LTE)',
    headset_display: 'U Mobile / MYS 18 / MY18',
    '3g_availability': true,
  },
]

const columns = {
  operator: {
    label: 'Operator',
  },
  headset_display: {
    label: 'Headset Display',
  },
  '3g_availability': {
    label: '3G Availability',
    format: (data: any) => (data ? 'Yes' : 'No'),
  },
}
// By passing using the Args format for exported stories, you can control the props for a component for reuse in a test
// https://storybook.js.org/docs/react/workflows/unit-testing
export const Default = Template.bind({})

Default.args = {
  data,
}
Default.parameters = {
  jest: 'Table',
}

export const Error = Template.bind({})

Error.args = {
  data: null,
}

Error.parameters = {
  jest: 'Error',
}

export const ColumnsMapping = Template.bind({})

ColumnsMapping.args = {
  title: 'Telecom List',
  data,
  columns,
}
ColumnsMapping.parameters = {
  jest: 'ColumnsMapping',
}

export const MoreColumns = Template.bind({})

MoreColumns.args = {
  title: 'Persons List',
  data: [
    {
      age: 33,
      eyeColor: 'blue',
      name: 'Kirkland Gilliam',
      gender: 'male',
      company: 'FIBEROX',
      email: 'kirklandgilliam@fiberox.com',
      phone: '+1 (914) 486-3195',
      salary: 15138.1,
      dependants: 1,
      experience: '9yrs 3months',
      techstack: 'Python',
      serving: true,
    },
    {
      age: 39,
      eyeColor: 'brown',
      name: 'Elsa Hayden',
      gender: 'female',
      email: 'elsahayden@comvene.com',
      phone: '+1 (917) 411-2284',
      salary: 176375.88,
      dependants: 1,
      experience: '1yrs 10months',
      techstack: 'Dot Net',
      serving: false,
    },
    {
      age: 33,
      name: 'Holmes Mooney',
      gender: 'male',
      company: 'OLUCORE',
      email: 'holmesmooney@olucore.com',
      phone: '+1 (964) 529-2279',
      salary: 91363.46,
      dependants: 1,
      experience: '18yrs 5months',
      techstack: 'R',
      serving: true,
    },
    {
      age: 34,
      eyeColor: 'green',
      name: 'Paige Dixon',
      gender: 'female',
      company: 'MANTRIX',
      phone: '+1 (857) 582-3516',
      salary: 229949.61,
      dependants: 3,
      experience: '17yrs 4months',
      techstack: 'Ruby',
      serving: true,
    },
    {
      age: 38,
      eyeColor: 'green',
      name: 'Alana Ramsey',
      company: 'SOPRANO',
      email: 'alanaramsey@soprano.com',
      phone: '+1 (977) 458-2974',
      salary: 78305.36,
      dependants: 4,
      experience: '25yrs 8months',
      techstack: 'C++',
      serving: false,
    },
    {
      age: 28,
      eyeColor: 'blue',
      name: 'Crystal Norton',
      gender: 'female',
      company: 'OPTYK',
      email: 'crystalnorton@optyk.com',
      phone: '+1 (998) 591-2416',
      salary: 27680.22,
      dependants: 1,
      serving: true,
    },
    {
      age: 24,
      eyeColor: 'green',
      name: 'Malone Mccarty',
      gender: 'male',
      company: 'GENMY',
      email: 'malonemccarty@genmy.com',
      phone: '+1 (850) 581-3077',
      salary: 117438.17,
      dependants: 2,
      experience: '7yrs 11months',
      techstack: 'R',
    },
    {
      age: 23,
      eyeColor: 'brown',
      name: 'Armstrong Mitchell',
      gender: 'male',
      company: 'EZENTIA',
      email: 'armstrongmitchell@ezentia.com',
      phone: '+1 (909) 425-3836',
      salary: 205145.65,
      experience: '7yrs 2months',
      techstack: 'Java',
      serving: true,
    },
    {
      age: 40,
      eyeColor: 'green',
      name: 'Jimenez Wong',
      gender: 'male',
      company: 'CAPSCREEN',
      email: 'jimenezwong@capscreen.com',
      phone: '+1 (943) 596-3247',
      salary: 180197.32,
      dependants: 1,
      experience: '7yrs 1months',
      techstack: 'JavaScript',
      serving: false,
    },
    {
      eyeColor: 'blue',
      name: 'Helena Blankenship',
      gender: 'female',
      company: 'GINKOGENE',
      email: 'helenablankenship@ginkogene.com',
      phone: '+1 (829) 577-3462',
      salary: 235654.04,
      dependants: 0,
      experience: '17yrs 6months',
      techstack: 'Java',
      serving: false,
    },
    {
      age: 35,
      eyeColor: 'green',
      name: 'Sheryl William',
      gender: 'female',
      company: 'MEDESIGN',
      email: 'sherylwilliam@medesign.com',
      phone: '+1 (960) 556-3522',
      salary: 41045.04,
      dependants: 0,
      experience: '5yrs 6months',
      techstack: 'PHP',
      serving: true,
    },
    {
      age: 24,
      eyeColor: 'blue',
      name: 'Mara Baird',
      gender: 'female',
      company: 'DIGIRANG',
      email: 'marabaird@digirang.com',
      phone: '+1 (971) 523-3509',
      salary: 180118.31,
      dependants: 1,
      experience: '13yrs 4months',
      techstack: 'JavaScript',
      serving: false,
    },
    {
      age: 34,
      eyeColor: 'brown',
      name: 'Melinda Graham',
      gender: 'female',
      company: 'ESCENTA',
      email: 'melindagraham@escenta.com',
      phone: '+1 (818) 508-2861',
      salary: 96692.48,
      dependants: 1,
      experience: '27yrs 3months',
      techstack: 'C',
      serving: false,
    },
    {
      age: 24,
      eyeColor: 'brown',
      name: 'Wiley Roberts',
      gender: 'male',
      company: 'GEEKY',
      email: 'wileyroberts@geeky.com',
      phone: '+1 (971) 517-3304',
      salary: 250435.88,
      dependants: 4,
      techstack: 'C',
      serving: false,
    },
    {
      age: 34,
      eyeColor: 'brown',
      name: 'Kellie Taylor',
      gender: 'female',
      company: 'NIPAZ',
      email: 'kellietaylor@nipaz.com',
      phone: '+1 (912) 534-2229',
      salary: 123607.82,
      dependants: 4,
      experience: '28yrs 5months',
      techstack: 'C++',
      serving: true,
    },
    {
      age: 31,
      eyeColor: 'green',
      name: 'Meghan Byers',
      gender: 'female',
      company: 'MEDALERT',
      email: 'meghanbyers@medalert.com',
      phone: '+1 (986) 570-2067',
      salary: 50014.57,
      dependants: 1,
      experience: '29yrs 9months',
      techstack: 'C',
      serving: true,
    },
    {
      age: 23,
      eyeColor: 'blue',
      name: 'English Sharpe',
      gender: 'male',
      company: 'COMBOGEN',
      email: 'englishsharpe@combogen.com',
      phone: '+1 (884) 493-3411',
      salary: 273209.54,
      dependants: 3,
      experience: '21yrs 10months',
      techstack: 'C',
      serving: true,
    },
    {
      age: 40,
      eyeColor: 'brown',
      name: 'Paula Bentley',
      gender: 'female',
      company: 'OPTIQUE',
      email: 'paulabentley@optique.com',
      phone: '+1 (982) 519-3533',
      salary: 166338.42,
      dependants: 1,
      experience: '21yrs 6months',
      techstack: 'JavaScript',
      serving: false,
    },
    {
      age: 22,
      eyeColor: 'green',
      name: 'Rosie Holloway',
      gender: 'female',
      company: 'HATOLOGY',
      email: 'rosieholloway@hatology.com',
      phone: '+1 (980) 497-3066',
      salary: 184205.75,
      dependants: 2,
      experience: '16yrs 1months',
      techstack: 'Ruby',
      serving: false,
    },
    {
      age: 24,
      eyeColor: 'blue',
      name: 'Rosanne Mckee',
      gender: 'female',
      company: 'KINETICUT',
      email: 'rosannemckee@kineticut.com',
      phone: '+1 (908) 592-3730',
      salary: 223544.47,
      dependants: 2,
      experience: '12yrs 4months',
      techstack: 'Python',
      serving: true,
    },
    {
      age: 39,
      eyeColor: 'brown',
      name: 'Sharon Parrish',
      gender: 'female',
      company: 'ROCKLOGIC',
      email: 'sharonparrish@rocklogic.com',
      phone: '+1 (884) 561-3744',
      salary: 250036.54,
      dependants: 3,
      experience: '9yrs 6months',
      techstack: 'Dot Net',
      serving: false,
    },
    {
      age: 29,
      eyeColor: 'green',
      name: 'Kari Webster',
      gender: 'female',
      company: 'AQUASSEUR',
      email: 'kariwebster@aquasseur.com',
      phone: '+1 (982) 420-3563',
      salary: 147319.69,
      dependants: 3,
      experience: '27yrs 2months',
      techstack: 'Ruby',
      serving: false,
    },
    {
      age: 40,
      eyeColor: 'blue',
      name: 'Leslie Lee',
      gender: 'female',
      company: 'EMTRAC',
      email: 'leslielee@emtrac.com',
      phone: '+1 (867) 504-3802',
      salary: 192554.71,
      dependants: 4,
      experience: '21yrs 9months',
      techstack: 'PHP',
      serving: false,
    },
    {
      age: 39,
      eyeColor: 'green',
      name: 'Goff Stevens',
      gender: 'male',
      company: 'ZILPHUR',
      email: 'goffstevens@zilphur.com',
      phone: '+1 (955) 545-3896',
      salary: 132921.12,
      dependants: 1,
      experience: '29yrs 6months',
      techstack: 'PHP',
      serving: true,
    },
    {
      age: 37,
      eyeColor: 'green',
      name: 'Bowers Snider',
      gender: 'male',
      company: 'IMMUNICS',
      email: 'bowerssnider@immunics.com',
      phone: '+1 (981) 461-2736',
      salary: 215846.13,
      dependants: 4,
      experience: '16yrs 2months',
      techstack: 'JavaScript',
      serving: true,
    },
    {
      age: 31,
      eyeColor: 'blue',
      name: 'Hicks Molina',
      gender: 'male',
      company: 'UTARA',
      email: 'hicksmolina@utara.com',
      phone: '+1 (983) 409-2621',
      salary: 230037.58,
      dependants: 4,
      experience: '19yrs 9months',
      techstack: 'Scala',
      serving: true,
    },
    {
      age: 40,
      eyeColor: 'blue',
      name: 'Evans Alford',
      gender: 'male',
      company: 'RONELON',
      email: 'evansalford@ronelon.com',
      phone: '+1 (904) 516-3020',
      salary: 192904.98,
      dependants: 1,
      experience: '27yrs 5months',
      techstack: 'PHP',
      serving: true,
    },
    {
      age: 33,
      eyeColor: 'blue',
      name: 'Jackie Hampton',
      gender: 'female',
      company: 'EQUICOM',
      email: 'jackiehampton@equicom.com',
      phone: '+1 (839) 452-2437',
      salary: 255378.09,
      dependants: 0,
      experience: '6yrs 9months',
      techstack: 'Haskel',
      serving: false,
    },
    {
      age: 31,
      eyeColor: 'green',
      name: 'Olive Banks',
      gender: 'female',
      company: 'EGYPTO',
      email: 'olivebanks@egypto.com',
      phone: '+1 (853) 530-2707',
      salary: 228828.11,
      dependants: 0,
      experience: '3yrs 5months',
      techstack: 'R',
      serving: true,
    },
    {
      age: 37,
      eyeColor: 'blue',
      name: 'Waters Estes',
      gender: 'male',
      company: 'MYOPIUM',
      email: 'watersestes@myopium.com',
      phone: '+1 (987) 404-3116',
      salary: 238392.78,
      dependants: 4,
      experience: '23yrs 11months',
      techstack: 'C++',
      serving: true,
    },
    {
      age: 34,
      eyeColor: 'brown',
      name: 'Newton Benton',
      gender: 'male',
      company: 'INCUBUS',
      email: 'newtonbenton@incubus.com',
      phone: '+1 (832) 418-3647',
      salary: 163263.57,
      dependants: 4,
      experience: '14yrs 5months',
      techstack: 'R',
      serving: true,
    },
    {
      age: 36,
      eyeColor: 'blue',
      name: 'Rosella Knox',
      gender: 'female',
      company: 'GEOLOGIX',
      email: 'rosellaknox@geologix.com',
      phone: '+1 (909) 534-2408',
      salary: 210801.33,
      dependants: 0,
      experience: '7yrs 9months',
      techstack: 'C++',
      serving: true,
    },
    {
      age: 20,
      eyeColor: 'blue',
      name: 'Michael Heath',
      gender: 'male',
      company: 'ZORK',
      email: 'michaelheath@zork.com',
      phone: '+1 (933) 476-2233',
      salary: 251780.81,
      dependants: 1,
      experience: '22yrs 4months',
      techstack: 'R',
      serving: false,
    },
    {
      age: 23,
      eyeColor: 'brown',
      name: 'Jami Rowe',
      gender: 'female',
      company: 'ZEDALIS',
      email: 'jamirowe@zedalis.com',
      phone: '+1 (977) 406-3595',
      salary: 116863.1,
      dependants: 1,
      experience: '6yrs 6months',
      techstack: 'C',
      serving: false,
    },
    {
      age: 25,
      eyeColor: 'green',
      name: 'Short Delacruz',
      gender: 'male',
      company: 'TRANSLINK',
      email: 'shortdelacruz@translink.com',
      phone: '+1 (866) 481-2262',
      salary: 46854.84,
      dependants: 2,
      experience: '20yrs 7months',
      techstack: 'PHP',
      serving: false,
    },
    {
      age: 22,
      eyeColor: 'blue',
      name: 'Alba Whitney',
      gender: 'female',
      company: 'VERTIDE',
      email: 'albawhitney@vertide.com',
      phone: '+1 (894) 543-2644',
      salary: 282450.04,
      dependants: 4,
      experience: '16yrs 10months',
      techstack: 'C',
      serving: false,
    },
    {
      age: 40,
      eyeColor: 'brown',
      name: 'Jeannette Finley',
      gender: 'female',
      company: 'EXOSPEED',
      email: 'jeannettefinley@exospeed.com',
      phone: '+1 (996) 494-2496',
      salary: 104104.02,
      dependants: 3,
      experience: '24yrs 2months',
      techstack: 'C',
      serving: false,
    },
    {
      age: 28,
      eyeColor: 'blue',
      name: 'Addie Alvarado',
      gender: 'female',
      company: 'VIRVA',
      email: 'addiealvarado@virva.com',
      phone: '+1 (883) 427-3582',
      salary: 195094.21,
      dependants: 2,
      experience: '5yrs 2months',
      techstack: 'PHP',
      serving: true,
    },
    {
      age: 40,
      eyeColor: 'blue',
      name: 'Ines Burt',
      gender: 'female',
      company: 'FROLIX',
      email: 'inesburt@frolix.com',
      phone: '+1 (998) 584-3087',
      salary: 271651.04,
      dependants: 3,
      experience: '9yrs 4months',
      techstack: 'Ruby',
      serving: false,
    },
    {
      age: 20,
      eyeColor: 'green',
      name: 'Cameron Hardy',
      gender: 'male',
      company: 'EDECINE',
      email: 'cameronhardy@edecine.com',
      phone: '+1 (842) 492-2366',
      salary: 37806.78,
      dependants: 3,
      experience: '15yrs 6months',
      techstack: 'JavaScript',
      serving: false,
    },
    {
      age: 39,
      eyeColor: 'blue',
      name: 'Taylor Nicholson',
      gender: 'male',
      company: 'UTARIAN',
      email: 'taylornicholson@utarian.com',
      phone: '+1 (890) 600-3462',
      salary: 130097.63,
      dependants: 3,
      experience: '6yrs 10months',
      techstack: 'PHP',
      serving: false,
    },
    {
      age: 23,
      eyeColor: 'green',
      name: 'Teri Fitzpatrick',
      gender: 'female',
      company: 'QIAO',
      email: 'terifitzpatrick@qiao.com',
      phone: '+1 (994) 575-2527',
      salary: 255670.33,
      dependants: 4,
      experience: '23yrs 10months',
      techstack: 'Go',
      serving: false,
    },
    {
      age: 34,
      eyeColor: 'brown',
      name: 'Richardson Skinner',
      gender: 'male',
      company: 'CAXT',
      email: 'richardsonskinner@caxt.com',
      phone: '+1 (984) 411-3536',
      salary: 191029.67,
      dependants: 4,
      experience: '21yrs 11months',
      techstack: 'Java',
      serving: true,
    },
    {
      age: 20,
      eyeColor: 'green',
      name: 'Marks Dorsey',
      gender: 'male',
      company: 'ENJOLA',
      email: 'marksdorsey@enjola.com',
      phone: '+1 (810) 448-2191',
      salary: 30291.48,
      dependants: 1,
      experience: '26yrs 4months',
      techstack: 'Java',
      serving: true,
    },
    {
      age: 37,
      eyeColor: 'green',
      name: 'Pace Lynch',
      gender: 'male',
      company: 'NIQUENT',
      email: 'pacelynch@niquent.com',
      phone: '+1 (862) 487-3196',
      salary: 53014.85,
      dependants: 0,
      experience: '4yrs 2months',
      techstack: 'Dot Net',
      serving: false,
    },
    {
      age: 39,
      eyeColor: 'green',
      name: 'Kirsten Farmer',
      gender: 'female',
      company: 'BOVIS',
      email: 'kirstenfarmer@bovis.com',
      phone: '+1 (916) 599-3842',
      salary: 21062.2,
      dependants: 2,
      experience: '9yrs 2months',
      techstack: 'Go',
      serving: false,
    },
    {
      age: 24,
      eyeColor: 'green',
      name: 'Vera Grant',
      gender: 'female',
      company: 'CYTREK',
      email: 'veragrant@cytrek.com',
      phone: '+1 (956) 543-3708',
      salary: 28769.9,
      dependants: 2,
      experience: '24yrs 9months',
      techstack: 'R',
      serving: false,
    },
    {
      age: 37,
      eyeColor: 'brown',
      name: 'Nola Wiley',
      gender: 'female',
      company: 'MICROLUXE',
      email: 'nolawiley@microluxe.com',
      phone: '+1 (926) 550-2581',
      salary: 161025.18,
      dependants: 2,
      experience: '29yrs 2months',
      techstack: 'R',
      serving: true,
    },
    {
      age: 35,
      eyeColor: 'blue',
      name: 'Stephens Pearson',
      gender: 'male',
      company: 'POWERNET',
      email: 'stephenspearson@powernet.com',
      phone: '+1 (934) 573-3472',
      salary: 109861.93,
      dependants: 0,
      experience: '11yrs 6months',
      techstack: 'Java',
      serving: true,
    },
    {
      age: 32,
      eyeColor: 'brown',
      name: 'Pitts Lane',
      gender: 'male',
      company: 'PETIGEMS',
      email: 'pittslane@petigems.com',
      phone: '+1 (978) 567-2022',
      salary: 127585.1,
      dependants: 3,
      experience: '15yrs 4months',
      techstack: 'Dot Net',
      serving: true,
    },
    {
      age: 37,
      eyeColor: 'green',
      name: 'Guthrie Andrews',
      gender: 'male',
      company: 'MAXEMIA',
      email: 'guthrieandrews@maxemia.com',
      phone: '+1 (868) 465-3799',
      salary: 215908.53,
      dependants: 4,
      experience: '28yrs 2months',
      techstack: 'JavaScript',
      serving: false,
    },
    {
      age: 28,
      eyeColor: 'green',
      name: 'Casey Justice',
      gender: 'female',
      company: 'AVIT',
      email: 'caseyjustice@avit.com',
      phone: '+1 (940) 457-2175',
      salary: 36071.04,
      dependants: 3,
      experience: '24yrs 7months',
      techstack: 'C',
      serving: true,
    },
    {
      age: 33,
      eyeColor: 'green',
      name: 'Stevens Holt',
      gender: 'male',
      company: 'VERTON',
      email: 'stevensholt@verton.com',
      phone: '+1 (860) 411-2575',
      salary: 228282.02,
      dependants: 0,
      experience: '13yrs 6months',
      techstack: 'Go',
      serving: false,
    },
    {
      age: 26,
      eyeColor: 'green',
      name: 'Lindsey Stone',
      gender: 'female',
      company: 'CALCU',
      email: 'lindseystone@calcu.com',
      phone: '+1 (851) 490-2876',
      salary: 244660.82,
      dependants: 2,
      experience: '20yrs 1months',
      techstack: 'R',
      serving: false,
    },
    {
      age: 39,
      eyeColor: 'brown',
      name: 'Shana Edwards',
      gender: 'female',
      company: 'CUBICIDE',
      email: 'shanaedwards@cubicide.com',
      phone: '+1 (948) 517-3331',
      salary: 234361.92,
      dependants: 1,
      experience: '16yrs 9months',
      techstack: 'PHP',
      serving: true,
    },
    {
      age: 32,
      eyeColor: 'blue',
      name: 'Aurora Bradford',
      gender: 'female',
      company: 'GENESYNK',
      email: 'aurorabradford@genesynk.com',
      phone: '+1 (958) 599-3474',
      salary: 165648.7,
      dependants: 4,
      experience: '27yrs 8months',
      techstack: 'Python',
      serving: true,
    },
  ],
  columns: {
    name: { label: 'Name', sortable: true },
    age: { label: 'Age', sortable: true },
    eyeColor: { label: 'Eye Color', sortable: true },
    gender: {
      label: 'Gender',
      format: (data: any) => (data === 'male' ? 'M' : 'F'),
    },
    company: { label: 'Company', sortable: true },
    email: { label: 'Email' },
    phone: { label: 'Phone' },
    salary: {
      label: 'Income',
      sortable: true,
      format: (data: any) => '$' + Math.ceil(data),
    },
    dependants: { label: 'Dependants', sortable: true },
    experience: { label: 'Experience', sortable: true },
    techstack: { label: 'Skills' },
    serving: {
      label: 'Serving',
      sortable: true,
      format: (data: any) => (data ? 'Yes' : 'No'),
    },
  },
}

MoreColumns.parameters = {
  jest: '',
}
